### ISSUE TITLE
Issue with typescript and declaration file

### ISSUE THREAD

**Issue by MercurialUroboros** [pixijs/pixi-projection#81]
Hello.
I'm using Pixi 5.3.3 with typescript 3.9.7 and webpack.

I'm facing an issue with pixi-projection declaration file.

Basically typescript is complaining about a declaration file being filled with actual code...and it's actually right about it.

Is there any solution for this? Apart from trying to make my ts ignore that .d file?

Regards

**Comment by ivanpopelyshev** [comment]
OMG, this again. Its problem for all my plugins. Gonna fix it soon :)

**Comment by ivanpopelyshev** [comment]
I fixed it before, i just forgot that we have two `d.ts` files, not one . Fixed, here and 0.3.14 npm.

**Comment by MercurialUroboros** [comment]
Thanks a lot for the fast fix!

**Comment by laxman-spidey** [comment]
@MercurialUroboros I was also facing the same issue earlier. Now it's gone. No compilation errors, but i'm still getting below error 
```
Uncaught ReferenceError: PIXI is not defined
    js pixi-projection.js:36
```
even after adding these lines before import. Can you help me how you solved this issue? (it's happening with other plugins as well)
`global.PIXI = PIXI;`
`window.PIXI = PIXI;`

Note: I'm working on Angular 10, typescript 3.9

**Comment by MercurialUroboros** [comment]
Regardless of what you are working with, I believe it's something you have to define in your webpack.
Have you tried this?

`      new webpack.ProvidePlugin({
        PIXI: 'pixi.js'
      })`

**Comment by laxman-spidey** [comment]
Modified angular to use custom webkit and configured the PIXI plugin with the line you have given then it worked. Thank you very much.
